export const POKEMONS_FETCHING = 'POKEMONS_FETCHING';
export const POKEMONS_FETCHED  = 'POKEMONS_FETCHED';
export const POKEMON_FETCHING  = 'POKEMON_FETCHING';
export const POKEMON_FETCHED   = 'POKEMON_FETCHED';